### ISSUE TITLE
I not able to scroll native drop down in iOS using Appium wdio,

### ISSUE THREAD

**Issue by jayshreekant** [webdriverio/appium-boilerplate#71] opened 2020-04-09 07:17 UTC
**Environment (please complete the following information):**
 - Node.js version: [12.16.1]
 - NPM version: [6.14.4]
 - Platform: [iOS]
 - Platform version: [12.4]
 - Emulator/Simulator/Real Device: [ Simulator]

**Describe the bug**
I could not find any wdio related code to click and scroll the dropdown, After selecting the desired value. I want to Click on "Done" button, Need help with it. 

**To Reproduce**
N/A
**Expected behavior**
User should be able to scroll a dropdown and select the desired value.
**Screenshots**
Image Attached
![drop down](https://user-images.githubusercontent.com/12380291/78868277-3ef64f00-7a60-11ea-8a4b-43356f52c3e4.png)

**Additional context**
N/A

**Comment by wswebcreation** [comment] 2020-04-09 07:23
Hi @jayshreekant 

This is not an issue with the boilerplate therefor I'm going to close it. You can check the _Done_ button selector with Appium Desktop and use the `element.addValue('Value')` to select the value in a pickerwheel or use  this method from Appium http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/#mobile-selectpickerwheelvalue

Also be aware that Appium and iOS 13 are currently not working properly

**Closed by wswebcreation** 2020-04-09 07:23 UTC

**Comment by jayshreekant** [comment] 2020-04-09 11:25
Wim you have created a helper method for this boiler plate project, I want to use that one.
I could not find anything helpful.

**Comment by wswebcreation** [comment] 2020-04-14 06:14
@jayshreekant 

Can you be a bit more clear what the problem is? The http://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/#mobile-selectpickerwheelvalue is doing what it needs to do and also what you explained. Don't know what you expect now
