### ISSUE TITLE
Error: spawn appium ENOENT  with appium and selenium grid, Unhandled 'error' event

### ISSUE THREAD

**Issue by sujiacong** [webdriverio/appium-boilerplate#35] opened 2020-01-16 06:10 UTC
**Environment (please complete the following information):**
 - Node.js version: [v10.15.0]
 - NPM version: [6.4.1]
 - Platform: [Android]
 - Platform version: [5.1.1]
 - Emulator/Simulator/Real Device: [Simulator]

**Describe the bug**
Error: spawn appium ENOENT when test with appium and selenium grid

**To Reproduce**
1、prepare docker appium/appium and docker selenium/hub in ubuntu 16.04 
2、prepare Simulator in windows7 using Nox at https://www.bignox.com/
3、start docker container and Simulator
4、git clone https://github.com/webdriverio/appium-boilerplate.git
5、download Android-NativeDemoApp-0.2.1.apk in appium-boilerplate/app dir
5、npm install
6、npm run android.app

**Expected behavior**
run appium-boilerplate test successful 

**Screenshots**

![gitdiff](https://user-images.githubusercontent.com/22270812/72498836-30d2d100-386b-11ea-96e5-254d01843982.jpg)

below is the appium docker running log

[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 3 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 4 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 2 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}
[HTTP] <-- GET /wd/hub/status 200 1 ms - 68
[HTTP] 
[HTTP] --> GET /wd/hub/status
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getStatus() with args: []
[debug] [GENERIC] Responding to client with driver.getStatus() result: {"build":{"version":"1.15.1"}}

**Additional context**
root@ubuntu:~/android_auto/appium-boilerplate# npm run android.app

> appium-boilerplate@5.3.1 android.app /root/android_auto/appium-boilerplate
> wdio ./config/wdio.android.app.conf.js

Execution of 6 spec files started at 2020-01-16T05:57:51.393Z

2020-01-16T05:57:51.403Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "appium"
2020-01-16T05:57:51.423Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-01-16T05:57:51.425Z DEBUG @wdio/appium-service: Will spawn Appium process: appium 
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn appium ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-boilerplate@5.3.1 android.app: `wdio ./config/wdio.android.app.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-boilerplate@5.3.1 android.app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-16T05_57_51_467Z-debug.log

**Comment by wswebcreation** [comment] 2020-01-16 06:56
Hi @sujiacong 

First of all this boilerplate is how to set up Appium with WebdriverIO on a local machine in a pretty straightforward way, not in the complex set up you are having. 

Having said that, to understand your setup, can you explain a bit more about your setup, because if you are running a Selenium Grid you register an Android/Apple device with it's own Appium server to the hub and you don't need to have the Appium service running. You should remove the service from the config. 

If that's the case and you are using a Selenium Gird without the Appium service I can't help you and would ask you to to close the issue and ask for help in different channels

**Comment by sujiacong** [comment] 2020-01-19 12:08
Sorry, the feedback is a bit late,thank you in advance for your answers.
I deployed with reference to appium on https://github.com/appium/appium-docker-android.
and was not very clear with the implementation details.

But I can open the app using the following python code,so the deployment should be correct.
![pythoncode](https://user-images.githubusercontent.com/22270812/72680637-2dec1080-3af7-11ea-9ae3-b5b204644416.jpg)

I have tried to  remove appium service,but it also failed.
Below is the log of the failure
![error](https://user-images.githubusercontent.com/22270812/72680622-f9785480-3af6-11ea-8b94-c41d8f470a5f.jpg)

![service](https://user-images.githubusercontent.com/22270812/72680660-786d8d00-3af7-11ea-962c-8f64582078bd.jpg)

**Comment by sujiacong** [comment] 2020-01-19 12:18
@wswebcreation 

I am using the followring shell scripts to start appium on ubuntu16.04.
simulator is on windows7, using socat.exe TCP4-LISTEN:5555,reuseaddr,fork TCP4:127.0.0.1:62001 to forwarding traffic.
can you try test this ?

`#!/bin/bash

auto_install_update_images()
{
    local docker_name=$1
    local time=$2
    if [ -z $1 ]
    then
        return;
    fi
    local latest_exists=`docker images|grep $docker_name |awk '{if($2=="latest") print $3}'`
    if [ "x$latest_exists" = "x" ]
    then
        docker pull $docker_name:latest
    else
        local latest_time=`docker inspect $docker_name:latest|grep -i created|awk '{print $2}'|tr -d ',"'`
        if [ "x$latest_time" != "x$time" ]
        then
            docker pull $docker_name:latest
        fi
    fi
}

auto_install_update_images appium/appium 2019-11-21T14:32:33.920949951Z
auto_install_update_images selenium/hub 2019-12-15T12:16:20.128203103Z

SELENIUM_HUB_NAME=selenium-hub
CONTAINER_APPIUM_NAME=appium-node-1
APPIUM_HOST=172.17.0.1
APPIUM_PORT=4723
SELENIUM_HOST=172.17.0.1
SELENIUM_PORT=4444
CONTAINER_APPIUM_NAME=appium-node-1
REMOTE_ADB=true
ANDROID_DEVICES=10.208.118.13:5555
REMOTE_ADB_POLLING_SEC=60
RELAXED_SECURITY=true
CONNECT_TO_GRID=true
CUSTOM_NODE_CONFIG=true

docker stop $SELENIUM_HUB_NAME >& /dev/null
docker stop $CONTAINER_APPIUM_NAME >& /dev/null
docker rm $SELENIUM_HUB_NAME >& /dev/null
docker rm $CONTAINER_APPIUM_NAME >& /dev/null
docker run -d --rm -p 4444:4444 --name $SELENIUM_HUB_NAME selenium/hub:latest
docker run -it --rm -p 4723:4723 -e ADT=$ADT -e REMOTE_ADB=$REMOTE_ADB -e ANDROID_DEVICES=$ANDROID_DEVICES -e REMOTE_ADB_POLLING_SEC=$REMOTE_ADB_POLLING_SEC -e CONNECT_TO_GRID=$CONNECT_TO_GRID -e APPIUM_HOST="$APPIUM_HOST" -e APPIUM_PORT=$APPIUM_PORT -e SELENIUM_HOST="$SELENIUM_HOST" -e SELENIUM_PORT=$SELENIUM_PORT -e RELAXED_SECURITY=$RELAXED_SECURITY -v /dev/bus/usb:/dev/bus/usb --name $CONTAINER_APPIUM_NAME appium/appium:latest`

**Comment by wswebcreation** [comment] 2020-01-25 14:35
Hi @sujiacong 

I've been looking into this and it now looks like you get a different error, it can't access the app. The problem is that I'm not grid expert and ain't able to help you with this, sorry.

You might need to take a look at the app path to see if you have it correct / have access to it.

I'm going to close this issue because this is not related to the boilerplate itself, but it's still open for discussion

**Closed by wswebcreation** 2020-01-25 14:35 UTC
Labels: more info needed
